name: aplikacja_gen_obraz_np
description: "ACAB"
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  provider: ^6.1.1
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.0.1
  share_plus: ^7.0.2
  just_audio: ^0.9.35
  shared_preferences: ^2.2.2
  path_provider: ^2.1.0
  image: ^4.1.4
  flutter_colorpicker: ^1.0.3
  vector_math: ^2.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/a4.wav
    - assets/sounds/b4.wav
    - assets/sounds/c4.wav
    - assets/sounds/d4.wav
    - assets/sounds/f4.wav
    - assets/sounds/g4.wav
    - assets/sounds/a5.wav
    - assets/sounds/b5.wav
    - assets/sounds/c5.wav
    - assets/sounds/d5.wav
    - assets/sounds/f5.wav
    - assets/sounds/g5.wav
